/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 01 01:26:33 KST 2018
 */

package it.yup.util;

import static org.evosuite.shaded.org.mockito.Mockito.mock;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.fail;

import java.util.Comparator;
import java.util.Enumeration;
import java.util.NoSuchElementException;
import java.util.Spliterator;
import java.util.Vector;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.UnaryOperator;
import java.util.stream.Stream;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.Test;
import org.junit.runner.RunWith;
import static org.evosuite.runtime.EvoAssertions.*;
@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class MetaVector_ESTest1 extends MetaVector_ESTest_scaffolding1 {
@BeforeClass
public static void initEvoSuiteFramework() {
String a = "aa";
}
@AfterClass
public static void exitEvoSuiteFramework() {
String a = "aa";
}

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(1, 1);
      Integer integer0 = new Integer(1);
      metaVector0.addElement(integer0);
      metaVector0.lastIndexOf((Object) metaVector0);
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = (Object) metaVector0;
      objectArray0[1] = (Object) metaVector0;
      objectArray0[2] = (Object) metaVector0;
      metaVector0.copyInto(objectArray0);
      Object object0 = metaVector0.firstElement();
      Enumeration enumeration0 = metaVector0.elements();
      assertNotNull(enumeration0);
      
      metaVector0.lastIndexOf(object0);
      // Undeclared exception!
      try { 
        metaVector0.setElementAt((Object) null, (-2360));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      int int0 = 0;
      Vector<Integer> vector0 = new Vector<Integer>(0);
      Integer integer0 = new Integer(0);
      vector0.add(integer0);
      metaVector0.removeAllElements();
      metaVector0.insertElementAt(vector0, 0);
      int int1 = 1437;
      Integer integer1 = new Integer(1437);
      vector0.add(integer1);
      UnaryOperator<Integer> unaryOperator0 = UnaryOperator.identity();
      vector0.replaceAll(unaryOperator0);
      vector0.add(integer1);
      metaVector0.removeElementAt(0);
      Object[] objectArray0 = new Object[0];
      metaVector0.size();
      // Undeclared exception!
      try { 
        metaVector0.copyInto(objectArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      int int0 = 0;
      Vector<Integer> vector0 = new Vector<Integer>(0);
      Integer integer0 = new Integer(0);
      vector0.add(integer0);
      metaVector0.removeAllElements();
      metaVector0.insertElementAt(vector0, 0);
      int int1 = 1437;
      Integer integer1 = new Integer(1437);
      vector0.add(integer1);
      UnaryOperator<Integer> unaryOperator0 = UnaryOperator.identity();
      vector0.replaceAll(unaryOperator0);
      Object[] objectArray0 = new Object[0];
      // Undeclared exception!
      try { 
        metaVector0.copyInto(objectArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      int int0 = 0;
      Vector<Integer> vector0 = new Vector<Integer>(0);
      Integer integer0 = new Integer(0);
      vector0.add(integer0);
      metaVector0.removeAllElements();
      metaVector0.insertElementAt(vector0, 0);
      int int1 = 1437;
      Integer integer1 = new Integer(1437);
      vector0.add(integer1);
      UnaryOperator<Integer> unaryOperator0 = UnaryOperator.identity();
      Function<Object, Integer> function0 = (Function<Object, Integer>) mock(Function.class, new ViolatedAssumptionAnswer());
      unaryOperator0.compose((Function<? super String, ? extends Integer>) function0);
      vector0.replaceAll(unaryOperator0);
      metaVector0.removeElementAt(0);
      Object object0 = metaVector0.clone();
      metaVector0.indexOf(object0);
      Object[] objectArray0 = new Object[0];
      // Undeclared exception!
      try { 
        metaVector0.copyInto(objectArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      Spliterator spliterator0 = metaVector0.spliterator();
      metaVector0.isEmpty();
      metaVector0.toString();
      metaVector0.addElement((Object) null);
      Object[] objectArray0 = new Object[9];
      metaVector0.firstElement();
      objectArray0[0] = (Object) metaVector0;
      Object object0 = new Object();
      objectArray0[1] = object0;
      objectArray0[2] = (Object) spliterator0;
      objectArray0[3] = (Object) "Multivector: ";
      objectArray0[4] = (Object) null;
      objectArray0[5] = (Object) null;
      objectArray0[6] = (Object) spliterator0;
      objectArray0[7] = (Object) "Multivector: ";
      objectArray0[8] = (Object) null;
      metaVector0.copyInto(objectArray0);
      assertEquals(9, objectArray0.length);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(0);
      metaVector0.toString();
      Integer integer0 = new Integer(0);
      metaVector0.contains(integer0);
      metaVector0.lastIndexOf((Object) "Multivector: ");
      metaVector0.addElement(integer0);
      metaVector0.subList(0, 0);
      metaVector0.stream();
      metaVector0.contains(integer0);
      metaVector0.lastElement();
      MetaVector metaVector1 = new MetaVector(0, (-1));
      // Undeclared exception!
      try { 
        metaVector1.insertElementAt(integer0, (-13));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      int int0 = 0;
      Vector<Integer> vector0 = new Vector<Integer>(0);
      metaVector0.removeAllElements();
      metaVector0.insertElementAt(vector0, 0);
      UnaryOperator<Integer> unaryOperator0 = UnaryOperator.identity();
      vector0.replaceAll(unaryOperator0);
      // Undeclared exception!
      try { 
        metaVector0.removeElementAt(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      Stream stream0 = metaVector0.parallelStream();
      metaVector0.size();
      metaVector0.addElement(stream0);
      Object object0 = new Object();
      int int0 = (-20);
      // Undeclared exception!
      try { 
        metaVector0.setElementAt(object0, (-20));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      Object[] objectArray0 = new Object[1];
      metaVector0.containsAll(metaVector0);
      MetaVector metaVector1 = new MetaVector();
      metaVector0.stream();
      metaVector0.toString();
      metaVector0.insertElementAt((Object) null, 0);
      objectArray0[0] = (Object) metaVector0;
      metaVector0.copyInto(objectArray0);
      // Undeclared exception!
      try { 
        metaVector1.lastElement();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector$MultiVectorEnumeration", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      metaVector0.spliterator();
      metaVector0.isEmpty();
      metaVector0.toString();
      metaVector0.addElement((Object) null);
      Integer integer0 = new Integer(410);
      metaVector0.indexOf((Object) integer0);
      // Undeclared exception!
      try { 
        metaVector0.indexOf((Object) null, 410);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector$MultiVectorEnumeration", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(3569, 3569);
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      metaVector0.forEach(consumer0);
      Vector<String> vector0 = new MetaVector(3569, 3569);
      String string0 = null;
      vector0.add((String) null);
      metaVector0.addElement(vector0);
      metaVector0.indexOf((Object) null);
      MetaVector metaVector1 = new MetaVector();
      metaVector0.removeElement(metaVector1);
      int int0 = 1;
      // Undeclared exception!
      try { 
        metaVector1.insertElementAt(metaVector0, 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      metaVector0.spliterator();
      metaVector0.isEmpty();
      metaVector0.toString();
      metaVector0.addElement((Object) null);
      // Undeclared exception!
      try { 
        metaVector0.setElementAt((Object) null, 235);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      metaVector0.isEmpty();
      Object object0 = new Object();
      metaVector0.add(0, object0);
      String string0 = "Y/<$)";
      metaVector0.spliterator();
      int int0 = 741;
      // Undeclared exception!
      try { 
        metaVector0.lastIndexOf((Object) "Y/<$)", 741);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(3569, 3569);
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      metaVector0.forEach(consumer0);
      Vector<String> vector0 = new Vector<String>();
      String string0 = null;
      vector0.add((String) null);
      metaVector0.addElement(vector0);
      // Undeclared exception!
      try { 
        metaVector0.indexOf((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(0, (-1));
      Integer integer0 = new Integer((-1));
      metaVector0.toString();
      metaVector0.addElement(integer0);
      String string0 = ")B=cP #jb2,]";
      metaVector0.contains(")B=cP #jb2,]");
      metaVector0.toString();
      metaVector0.size();
      metaVector0.stream();
      // Undeclared exception!
      try { 
        metaVector0.elementAt((-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      Vector<Integer> vector0 = new Vector<Integer>(0);
      metaVector0.removeAllElements();
      metaVector0.insertElementAt(vector0, 0);
      Integer integer0 = new Integer(1437);
      vector0.add(integer0);
      UnaryOperator<Integer> unaryOperator0 = UnaryOperator.identity();
      vector0.replaceAll(unaryOperator0);
      metaVector0.removeElementAt(0);
      metaVector0.removeAllElements();
      // Undeclared exception!
      try { 
        metaVector0.setElementAt(vector0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      // Undeclared exception!
      try { 
        metaVector0.insertElementAt((Object) null, 787);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Object[] objectArray0 = new Object[6];
      MetaVector metaVector0 = new MetaVector();
      metaVector0.lastIndexOf(objectArray0[1], (-2288));
      metaVector0.removeElement("");
      // Undeclared exception!
      try { 
        metaVector0.removeElementAt((-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      Stream stream0 = metaVector0.parallelStream();
      int int0 = metaVector0.size();
      assertEquals(0, int0);
      
      metaVector0.addElement(stream0);
      Object object0 = new Object();
      metaVector0.setElementAt(object0, 0);
      metaVector0.removeAllElements();
      int int1 = metaVector0.indexOf((Object) stream0, 0);
      assertEquals((-1), int1);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      int int0 = (-1);
      MetaVector metaVector0 = null;
      try {
        metaVector0 = new MetaVector((-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -1
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(0);
      Integer integer0 = new Integer(336);
      int int0 = metaVector0.indexOf((Object) integer0, 0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(0, 0);
      Vector<String> vector0 = new Vector<String>(0);
      vector0.spliterator();
      metaVector0.stream();
      metaVector0.removeElement(vector0);
      metaVector0.isEmpty();
      metaVector0.addElement(vector0);
      metaVector0.isEmpty();
      metaVector0.size();
      // Undeclared exception!
      try { 
        metaVector0.firstElement();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      String string0 = "1e9=Jd=\"Xce)0a";
      metaVector0.lastIndexOf((Object) "1e9=Jd=\"Xce)0a");
      Comparator<String> comparator0 = (Comparator<String>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      metaVector0.sort(comparator0);
      // Undeclared exception!
      try { 
        metaVector0.removeElementAt((-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      // Undeclared exception!
      try { 
        metaVector0.removeElementAt(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      String string0 = "";
      metaVector0.addElement("");
      metaVector0.indexOf((Object) "", (-1));
      metaVector0.removeAllElements();
      metaVector0.removeAllElements();
      Object[] objectArray0 = new Object[7];
      objectArray0[0] = (Object) metaVector0;
      // Undeclared exception!
      try { 
        metaVector0.set(0, "");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(769, 769);
      // Undeclared exception!
      try { 
        metaVector0.lastElement();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector$MultiVectorEnumeration", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(0);
      Enumeration enumeration0 = metaVector0.elements();
      // Undeclared exception!
      try { 
        metaVector0.insertElementAt(enumeration0, (-1240));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      metaVector0.isEmpty();
      String string0 = "Y/<$)";
      metaVector0.spliterator();
      int int0 = 741;
      // Undeclared exception!
      try { 
        metaVector0.lastIndexOf((Object) "Y/<$)", 741);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      int int0 = 0;
      MetaVector metaVector0 = new MetaVector(0);
      int int1 = 0;
      metaVector0.listIterator(0);
      Object[] objectArray0 = new Object[2];
      Object object0 = metaVector0.clone();
      metaVector0.removeAllElements();
      // Undeclared exception!
      try { 
        metaVector0.setElementAt(object0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      int int0 = (-1);
      MetaVector metaVector1 = null;
      try {
        metaVector1 = new MetaVector((-1), (-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -1
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      int int0 = 1054;
      MetaVector metaVector0 = new MetaVector(1054, (-1659));
      Comparator<String> comparator0 = (Comparator<String>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      metaVector0.sort(comparator0);
      metaVector0.toString();
      // Undeclared exception!
      try { 
        metaVector0.elementAt(1054);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      int int0 = 0;
      MetaVector metaVector0 = new MetaVector(0, 1);
      Object object0 = null;
      metaVector0.elements();
      // Undeclared exception!
      try { 
        metaVector0.indexOf((Object) null, 1);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector$MultiVectorEnumeration", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(0, (-1523));
      metaVector0.isEmpty();
      // Undeclared exception!
      try { 
        metaVector0.setElementAt((Object) null, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(0);
      metaVector0.toString();
      metaVector0.elements();
      metaVector0.indexOf((Object) "Multivector: ");
      metaVector0.size();
      Object[] objectArray0 = new Object[0];
      metaVector0.copyInto(objectArray0);
      Vector<String> vector0 = new Vector<String>(metaVector0);
      // Undeclared exception!
      try { 
        metaVector0.indexOf((Object) vector0, 2060);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector$MultiVectorEnumeration", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      metaVector0.contains("f>e0u m\"");
      Enumeration enumeration0 = metaVector0.elements();
      assertNotNull(enumeration0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(0);
      metaVector0.removeElement((Object) null);
      Integer integer0 = new Integer(0);
      metaVector0.insertElementAt(integer0, 0);
      Enumeration enumeration0 = metaVector0.elements();
      metaVector0.isEmpty();
      metaVector0.toString();
      metaVector0.elements();
      metaVector0.lastElement();
      Integer integer1 = new Integer(0);
      metaVector0.addElement(integer1);
      Object object0 = metaVector0.firstElement();
      metaVector0.removeElement((Object) null);
      metaVector0.removeAllElements();
      metaVector0.lastIndexOf((Object) "Multivector:  0", 0);
      metaVector0.lastIndexOf(object0);
      metaVector0.lastIndexOf((Object) enumeration0, 0);
      metaVector0.removeAllElements();
      metaVector0.toString();
      metaVector0.removeAllElements();
      metaVector0.elements();
      // Undeclared exception!
      try { 
        metaVector0.lastIndexOf((Object) integer0, 164);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(0);
      metaVector0.removeElement((Object) null);
      Integer integer0 = new Integer(0);
      metaVector0.insertElementAt(integer0, 0);
      Enumeration enumeration0 = metaVector0.elements();
      metaVector0.isEmpty();
      metaVector0.toString();
      metaVector0.elements();
      metaVector0.lastElement();
      Integer integer1 = new Integer(0);
      metaVector0.addElement(integer1);
      Object object0 = metaVector0.firstElement();
      metaVector0.removeAllElements();
      metaVector0.lastIndexOf((Object) "Multivector:  0", 0);
      metaVector0.lastIndexOf(object0);
      metaVector0.lastIndexOf((Object) enumeration0, 0);
      metaVector0.removeAllElements();
      metaVector0.toString();
      metaVector0.removeAllElements();
      metaVector0.elements();
      // Undeclared exception!
      try { 
        metaVector0.lastIndexOf((Object) integer0, 164);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector(0, 0);
      metaVector0.clone();
      metaVector0.size();
      // Undeclared exception!
      try { 
        metaVector0.firstElement();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      int int0 = 0;
      Vector<Integer> vector0 = new Vector<Integer>(0);
      Integer integer0 = new Integer(0);
      vector0.add(integer0);
      metaVector0.removeAllElements();
      metaVector0.insertElementAt(vector0, 0);
      int int1 = 1437;
      Integer integer1 = new Integer(1437);
      vector0.add(integer1);
      UnaryOperator<Integer> unaryOperator0 = UnaryOperator.identity();
      vector0.replaceAll(unaryOperator0);
      metaVector0.removeElementAt(0);
      Object[] objectArray0 = new Object[0];
      // Undeclared exception!
      try { 
        metaVector0.copyInto(objectArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      int int0 = 0;
      Vector<Integer> vector0 = new Vector<Integer>(0);
      Integer integer0 = new Integer(0);
      metaVector0.removeElement(vector0);
      metaVector0.removeAllElements();
      metaVector0.insertElementAt(vector0, 0);
      int int1 = 1437;
      Integer integer1 = new Integer(1437);
      // Undeclared exception!
      try { 
        metaVector0.setElementAt(integer1, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      int int0 = 0;
      MetaVector metaVector0 = new MetaVector(0);
      int int1 = 0;
      Stream stream0 = metaVector0.parallelStream();
      Vector<Object> vector0 = new Vector<Object>(0, 0);
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      vector0.forEach(consumer0);
      vector0.add((Object) stream0);
      metaVector0.removeAll(vector0);
      // Undeclared exception!
      try { 
        metaVector0.forEach((Consumer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      MetaVector metaVector0 = new MetaVector();
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = (Object) metaVector0;
      int int0 = 0;
      metaVector0.subList(0, 0);
      objectArray0[1] = (Object) metaVector0;
      objectArray0[2] = (Object) metaVector0;
      Object[] objectArray1 = metaVector0.toArray(objectArray0);
      metaVector0.isEmpty();
      metaVector0.contains("");
      metaVector0.copyInto(objectArray1);
      metaVector0.size();
      metaVector0.size();
      metaVector0.indexOf(objectArray0[2]);
      metaVector0.listIterator(0);
      MetaVector metaVector1 = new MetaVector(0);
      metaVector1.clone();
      metaVector0.indexOf((Object) metaVector1);
      metaVector0.isEmpty();
      Object object0 = new Object();
      metaVector1.toArray(objectArray1);
      metaVector1.remove((Object) null);
      // Undeclared exception!
      try { 
        metaVector0.insertElementAt(object0, (-3161));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.yup.util.MetaVector", e);
      }
  }
}
